// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

#ifndef PROTOBUF_service_2eproto__INCLUDED
#define PROTOBUF_service_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_service_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsService_Property_PropertyEntry_DoNotUseImpl();
void InitDefaultsService_Property_PropertyEntry_DoNotUse();
void InitDefaultsService_PropertyImpl();
void InitDefaultsService_Property();
void InitDefaultsServiceImpl();
void InitDefaultsService();
inline void InitDefaults() {
  InitDefaultsService_Property_PropertyEntry_DoNotUse();
  InitDefaultsService_Property();
  InitDefaultsService();
}
}  // namespace protobuf_service_2eproto
namespace sdc {
class Service;
class ServiceDefaultTypeInternal;
extern ServiceDefaultTypeInternal _Service_default_instance_;
class Service_Property;
class Service_PropertyDefaultTypeInternal;
extern Service_PropertyDefaultTypeInternal _Service_Property_default_instance_;
class Service_Property_PropertyEntry_DoNotUse;
class Service_Property_PropertyEntry_DoNotUseDefaultTypeInternal;
extern Service_Property_PropertyEntry_DoNotUseDefaultTypeInternal _Service_Property_PropertyEntry_DoNotUse_default_instance_;
}  // namespace sdc
namespace sdc {

// ===================================================================

class Service_Property_PropertyEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Service_Property_PropertyEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<Service_Property_PropertyEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  Service_Property_PropertyEntry_DoNotUse();
  Service_Property_PropertyEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Service_Property_PropertyEntry_DoNotUse& other);
  static const Service_Property_PropertyEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Service_Property_PropertyEntry_DoNotUse*>(&_Service_Property_PropertyEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Service_Property : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sdc.Service.Property) */ {
 public:
  Service_Property();
  virtual ~Service_Property();

  Service_Property(const Service_Property& from);

  inline Service_Property& operator=(const Service_Property& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Service_Property(Service_Property&& from) noexcept
    : Service_Property() {
    *this = ::std::move(from);
  }

  inline Service_Property& operator=(Service_Property&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Service_Property& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Service_Property* internal_default_instance() {
    return reinterpret_cast<const Service_Property*>(
               &_Service_Property_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Service_Property* other);
  friend void swap(Service_Property& a, Service_Property& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Service_Property* New() const PROTOBUF_FINAL { return New(NULL); }

  Service_Property* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Service_Property& from);
  void MergeFrom(const Service_Property& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Service_Property* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> Property = 1;
  int property_size() const;
  void clear_property();
  static const int kPropertyFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      property() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_property();

  // @@protoc_insertion_point(class_scope:sdc.Service.Property)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      Service_Property_PropertyEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > property_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_2eproto::TableStruct;
  friend void ::protobuf_service_2eproto::InitDefaultsService_PropertyImpl();
};
// -------------------------------------------------------------------

class Service : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sdc.Service) */ {
 public:
  Service();
  virtual ~Service();

  Service(const Service& from);

  inline Service& operator=(const Service& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Service(Service&& from) noexcept
    : Service() {
    *this = ::std::move(from);
  }

  inline Service& operator=(Service&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Service& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Service* internal_default_instance() {
    return reinterpret_cast<const Service*>(
               &_Service_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Service* other);
  friend void swap(Service& a, Service& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Service* New() const PROTOBUF_FINAL { return New(NULL); }

  Service* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Service& from);
  void MergeFrom(const Service& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Service* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Service_Property Property;

  // accessors -------------------------------------------------------

  // repeated .sdc.Service.Property Properties = 3;
  int properties_size() const;
  void clear_properties();
  static const int kPropertiesFieldNumber = 3;
  const ::sdc::Service_Property& properties(int index) const;
  ::sdc::Service_Property* mutable_properties(int index);
  ::sdc::Service_Property* add_properties();
  ::google::protobuf::RepeatedPtrField< ::sdc::Service_Property >*
      mutable_properties();
  const ::google::protobuf::RepeatedPtrField< ::sdc::Service_Property >&
      properties() const;

  // string ServiceName = 1;
  void clear_servicename();
  static const int kServiceNameFieldNumber = 1;
  const ::std::string& servicename() const;
  void set_servicename(const ::std::string& value);
  #if LANG_CXX11
  void set_servicename(::std::string&& value);
  #endif
  void set_servicename(const char* value);
  void set_servicename(const char* value, size_t size);
  ::std::string* mutable_servicename();
  ::std::string* release_servicename();
  void set_allocated_servicename(::std::string* servicename);

  // string Address = 2;
  void clear_address();
  static const int kAddressFieldNumber = 2;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  #if LANG_CXX11
  void set_address(::std::string&& value);
  #endif
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // @@protoc_insertion_point(class_scope:sdc.Service)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::sdc::Service_Property > properties_;
  ::google::protobuf::internal::ArenaStringPtr servicename_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_2eproto::TableStruct;
  friend void ::protobuf_service_2eproto::InitDefaultsServiceImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Service_Property

// map<string, string> Property = 1;
inline int Service_Property::property_size() const {
  return property_.size();
}
inline void Service_Property::clear_property() {
  property_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Service_Property::property() const {
  // @@protoc_insertion_point(field_map:sdc.Service.Property.Property)
  return property_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Service_Property::mutable_property() {
  // @@protoc_insertion_point(field_mutable_map:sdc.Service.Property.Property)
  return property_.MutableMap();
}

// -------------------------------------------------------------------

// Service

// string ServiceName = 1;
inline void Service::clear_servicename() {
  servicename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Service::servicename() const {
  // @@protoc_insertion_point(field_get:sdc.Service.ServiceName)
  return servicename_.GetNoArena();
}
inline void Service::set_servicename(const ::std::string& value) {
  
  servicename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sdc.Service.ServiceName)
}
#if LANG_CXX11
inline void Service::set_servicename(::std::string&& value) {
  
  servicename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sdc.Service.ServiceName)
}
#endif
inline void Service::set_servicename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  servicename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sdc.Service.ServiceName)
}
inline void Service::set_servicename(const char* value, size_t size) {
  
  servicename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sdc.Service.ServiceName)
}
inline ::std::string* Service::mutable_servicename() {
  
  // @@protoc_insertion_point(field_mutable:sdc.Service.ServiceName)
  return servicename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Service::release_servicename() {
  // @@protoc_insertion_point(field_release:sdc.Service.ServiceName)
  
  return servicename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Service::set_allocated_servicename(::std::string* servicename) {
  if (servicename != NULL) {
    
  } else {
    
  }
  servicename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), servicename);
  // @@protoc_insertion_point(field_set_allocated:sdc.Service.ServiceName)
}

// string Address = 2;
inline void Service::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Service::address() const {
  // @@protoc_insertion_point(field_get:sdc.Service.Address)
  return address_.GetNoArena();
}
inline void Service::set_address(const ::std::string& value) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sdc.Service.Address)
}
#if LANG_CXX11
inline void Service::set_address(::std::string&& value) {
  
  address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sdc.Service.Address)
}
#endif
inline void Service::set_address(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sdc.Service.Address)
}
inline void Service::set_address(const char* value, size_t size) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sdc.Service.Address)
}
inline ::std::string* Service::mutable_address() {
  
  // @@protoc_insertion_point(field_mutable:sdc.Service.Address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Service::release_address() {
  // @@protoc_insertion_point(field_release:sdc.Service.Address)
  
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Service::set_allocated_address(::std::string* address) {
  if (address != NULL) {
    
  } else {
    
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:sdc.Service.Address)
}

// repeated .sdc.Service.Property Properties = 3;
inline int Service::properties_size() const {
  return properties_.size();
}
inline void Service::clear_properties() {
  properties_.Clear();
}
inline const ::sdc::Service_Property& Service::properties(int index) const {
  // @@protoc_insertion_point(field_get:sdc.Service.Properties)
  return properties_.Get(index);
}
inline ::sdc::Service_Property* Service::mutable_properties(int index) {
  // @@protoc_insertion_point(field_mutable:sdc.Service.Properties)
  return properties_.Mutable(index);
}
inline ::sdc::Service_Property* Service::add_properties() {
  // @@protoc_insertion_point(field_add:sdc.Service.Properties)
  return properties_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::sdc::Service_Property >*
Service::mutable_properties() {
  // @@protoc_insertion_point(field_mutable_list:sdc.Service.Properties)
  return &properties_;
}
inline const ::google::protobuf::RepeatedPtrField< ::sdc::Service_Property >&
Service::properties() const {
  // @@protoc_insertion_point(field_list:sdc.Service.Properties)
  return properties_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sdc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_service_2eproto__INCLUDED
